" darkgrid.vim
" Approximate colorscheme based on provided screenshot
" Author: autogenerated
" Usage: :colorscheme darkgrid

set background=dark
hi clear
if exists("syntax_on")
  syntax reset
  endif

let g:colors_name = "darkgrid"

" --- Base palette ---
" Background / foreground
let s:bg        = "#1e1e1e"
let s:fg        = "#d4d4d4"
let s:fg_dim    = "#9da1a6"

" Accents
let s:cyan      = "#4fc1ff"
let s:blue      = "#569cd6"
let s:green     = "#6a9955"
let s:yellow    = "#dcdcaa"
let s:orange    = "#ce9178"
let s:purple    = "#c586c0"
let s:red       = "#f44747"
let s:gray      = "#3c3c3c"
let s:gray2     = "#2a2a2a"

" --- UI ---
hi Normal        guifg=s:fg       guibg=s:bg
hi Cursor        guifg=s:bg       guibg=s:fg
hi CursorLine    guibg=s:gray2
hi CursorColumn  guibg=s:gray2
hi LineNr        guifg=s:fg_dim   guibg=s:bg
hi CursorLineNr  guifg=s:yellow  guibg=s:gray2

hi StatusLine    guifg=s:fg       guibg=s:gray
hi StatusLineNC  guifg=s:fg_dim   guibg=s:gray2
hi VertSplit     guifg=s:gray     guibg=s:gray

hi Visual        guibg="#264f78"
hi Search        guifg=s:bg       guibg=s:yellow
hi IncSearch     guifg=s:bg       guibg=s:orange

hi Pmenu         guifg=s:fg       guibg=s:gray
hi PmenuSel      guifg=s:bg       guibg=s:blue
hi PmenuSbar     guibg=s:gray2
hi PmenuThumb    guibg=s:fg_dim

"" --- Syntax ---
hi Comment       guifg=s:green    gui=italic
hi Constant      guifg=s:orange
hi String        guifg=s:orange
hi Character    guifg=s:orange
hi Number        guifg=s:purple
hi Boolean       guifg=s:purple
hi Float         guifg=s:purple

hi Identifier    guifg=s:cyan
hi Function      guifg=s:yellow

hi Statement     guifg=s:blue
hi Conditional   guifg=s:blue
hi Repeat        guifg=s:blue
hi Label         guifg=s:blue
hi Operator      guifg=s:fg
hi Keyword       guifg=s:blue
hi Exception     guifg=s:blue

hi PreProc       guifg=s:purple
hi Include       guifg=s:purple
hi Define        guifg=s:purple
hi Macro         guifg=s:purple
hi PreCondit     guifg=s:purple

hi Type          guifg=s:cyan
hi StorageClass  guifg=s:cyan
hi Structure     guifg=s:cyan
hi Typedef       guifg=s:cyan

hi Special       guifg=s:yellow
hi SpecialChar   guifg=s:yellow
hi Tag           guifg=s:yellow
hi Delimiter     guifg=s:fg
hi SpecialComment guifg=s:green
hi Debug         guifg=s:red

hi Error         guifg=s:red      guibg=s:bg      gui=bold
hi Todo          guifg=s:purple  guibg=s:bg      gui=bold

" --- Diff ---
hi DiffAdd       guibg="#2a4f2a"
hi DiffChange    guibg="#3a3a2a"
hi DiffDelete    guibg="#4f2a2a"
hi DiffText      guibg="#264f78"

" --- Diagnostics (LSP) ---
hi DiagnosticError guifg=s:red
hi DiagnosticWarn  guifg=s:yellow
hi DiagnosticInfo  guifg=s:blue
hi DiagnosticHint  guifg=s:cyan
